# locust/Dockerfile.locust
FROM python:3.9-slim-buster

WORKDIR /locust

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY locustfile.py .

EXPOSE 8089

CMD ["locust", "-f", "locustfile.py"]
